---
nginx_revproxy_sites:
  monitoring.imarketingtest.kz:
    domains:
      - prometheus.imarketingtest.kz
      - alertmanager.imarketingtest.kz
      - grafana.imarketingtest.kz
    upstreams:
      - { backend_address: localhost, backend_port: 9090, name: prometheus }  # Prometheus
      - { backend_address: localhost, backend_port: 9100, name: node  }  # Node Exporter
      - { backend_address: localhost, backend_port: 9093, name: alert  }  # Alertmanager
      - { backend_address: localhost, backend_port: 3000, name: grafana  }  # Grafana
    ssl: true
    letsencrypt: true
    letsencrypt_email: 011@i-marketing.kz
    auth: true